Add airdrop dapp
FuelLabs/sway-examples pull request #18
Opened 2024-09-24 06:55 UTC by Nazeeh21

2024-11-27 20:58 UTC, calldelegation requested changes
1. I couldn't get it to work following your tests on the frontend. Maybe we can hop on a call to walk through it together

2. We should try to remove as much unnecessary commented code that is not going to be used as this is a public developer facing example and we should keep this as clean as possible. I have marked down several examples but didnt want to spam this PR with all of them.

3. There needs to be more comprehensive testing against your contract walking through the most common user flows of your applications

2024-11-27 20:58 UTC, calldelegation commented on airdrop/README.md
> +1. Start the Fuel development server. This server will start a local Fuel node and provide hot-reloading for your smart contracts.
1. This is cool but I cannot get it to work locally following these instructions. The contract deploys fine on my local network but I cannot see anything reflecting on the UI.
![Screen Shot 2024-11-27 at 15 28 08 PM  1](https://github.com/user-attachments/assets/9b2e4566-d3b3-43d7-bb92-977011fdd7d2)

2. Is there a hosted version like the other applications?

2024-11-27 20:58 UTC, calldelegation commented on airdrop/README.md
> +## Deploying to Testnet
Can you update the `readme` in the root of the projects to reflect the correct links as well?

2024-11-27 20:58 UTC, calldelegation commented on airdrop/src/components/NavMenu.tsx
> +  /* <NavigationMenu className="flex mt-3 w-full justify-around">
We need to delete these unused comments especially because this is a developer facing demo application

2024-11-27 20:58 UTC, calldelegation commented on airdrop/src/components/NavMenu.tsx
> +  // const [isDarkMode, setIsDarkMode] = useState(() => {
Unused comments

2024-11-27 20:58 UTC, calldelegation commented on airdrop/src/components/WalletDisplay.tsx
> +  // const CopyIcon = darkMode ? CopyIconDark : CopyIconLight;
Unused comment

2024-11-27 20:58 UTC, calldelegation commented on airdrop/src/components/ui/textarea.tsx
> +// export const MultilineInput: React.FC<{
Unused comment

2024-11-27 20:58 UTC, calldelegation commented on airdrop/sway-programs/contract/tests/harness.rs
> +    println!("Owner: {:?}", owner_result.value);
These should not be just prints but assertions

2024-11-27 20:58 UTC, calldelegation commented on airdrop/sway-programs/contract/tests/harness.rs
> +    println!("Owner: {:?}", owner_result.value);
Ahhh i see you put the assertions at the bottom. Maybe we should decouple all of these into separate tests to improve clarity on each functionality of your contract.

2024-11-27 20:58 UTC, calldelegation commented on airdrop/sway-programs/contract/tests/harness.rs
> +    let is_claimed_result = contract_instance.methods().is_claimed(tree_index).call().await.unwrap();
Can you write a tests to go through a real merkle hash and someone successfully making a claim against it?
Failure tests against only owner functionalities so its easier for developers to understand what is happening within your Sway contract

2024-11-27 21:51 UTC, matt-user requested changes
Good pr.  In the future review your own pr on GitHub.  There is a lot of low hanging fruit that can be caught before reviews.

2024-11-27 21:51 UTC, matt-user commented on airdrop/package-lock.json
We shouldn't need this file. The root pnpm-lock is what locks all dependencies

2024-11-27 21:51 UTC, matt-user commented on airdrop/playwright.config.ts
If you added front end tests add them to the ci

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/components/HomeCard.tsx
> +  console.log({ isEligible });
```suggestion
```

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/components/HomeCard.tsx
> +        // pointerEvents: isEligible ? "auto" : "none",
Remove comment

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/components/HomeCard.tsx
> +        padding: "18px",
Is there a light dark toggle?  If not look into tailwind for css but we can do this in a separate pr

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/components/Layout.tsx
> +        {/* <Navbar /> */}
Remove comment

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/components/NavMenu.tsx
> +          {/* <ModeToggle /> */}
Remove comments

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/components/Navbar.tsx
> +  const {
We shouldn't need this hook.  We should just have 1 wallet hook

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/components/Navbar.tsx
> +        {/* <Link href="/airdrop">Airdrop</Link> */}
Remove comment

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/components/WalletDisplay.tsx
> +export const getTruncatedAddress = (address: string) => {
These functions can go in a utility file

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/components/ui/date-picker.tsx
> +"use client";
We aren't using next right?  We should remove this

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/hooks/useBrowserWallet.tsx
> +export const useBrowserWallet: () => BrowserWallet = () => {
We don't need this hook

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/hooks/useBurnerWallet.tsx
> +export const useBurnerWallet: () => AppWallet = () => {
We don't need this hook

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/hooks/useClaimAirdrop.ts
> +      console.log(`temp`, temp);
Remove log

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/hooks/useDeployAirdrop.ts
> +      console.log(`temp`, temp);
Remove log

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/hooks/useGetAirdropActive.tsx
> +        // const isActive = await contract.functions.
Remove comment and remove try catch if you don't handle an error

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/lib.ts
> +// CURRENT_ENVIRONMENT === Environments.LOCAL
Remove commented code

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/lib.ts
> +  // @ts-expect-error will fix it once the build succeeds
Remove ts expect error and fix the error

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/main.tsx
> +      {/* <AppProvider> */}
Remove comments

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/routeTree.gen.ts
> +/* prettier-ignore-end */
Remove comments

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/routes/airdrop/claim/$slug.lazy.tsx
> +// import { IdentityInput } from "@/contract-types/aidrop-contracts/contracts/AirdropContract";
Remove comments

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/routes/airdrop/claim/$slug.lazy.tsx
> +  // @ts-expect-error will fix it once the build succeeds
Remove expect error

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/routes/airdrop/claim/$slug.lazy.tsx
> +  // console.log(endTime?.toNumber())
Remove

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/routes/airdrop/create.lazy.tsx
> +  // const {mutateAsync, data: ipfsData, isSuccess: uploadToIpfsSuccess} = useUploadAirdropData();
Remove

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/routes/airdrop/index.lazy.tsx
> +  useAsync(async () => {
Remove as it doesn't do anything

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/utils/airdropEligibility.ts
> +  let temp = undefined;
Rename variable.  Maybe possibleRecipient

2024-11-27 21:51 UTC, matt-user commented on airdrop/src/utils/merkleTrees.ts
> +  // const leafCoder = new TupleCoder([
Remove comments

2024-11-29 06:18 UTC, Nazeeh21 commented on airdrop/sway-programs/contract/tests/harness.rs
> +    println!("Owner: {:?}", owner_result.value);
I added these tests to debug a bug. We can add proper testing in a separate PR.

2024-11-29 06:19 UTC, Nazeeh21 commented on airdrop/playwright.config.ts
For now, I have removed TS tests, as they were added to test a bug

2024-11-29 06:21 UTC, Nazeeh21 commented on airdrop/src/components/HomeCard.tsx
> +        padding: "18px",
I am using Shadcn to toggle modes. But I will need to modify some CSS classes and properties to apply it completely. And agreed can be done into a separate PR.

2024-11-29 06:24 UTC, Nazeeh21 commented on airdrop/src/components/Navbar.tsx
> +  const {
I am not using this file anymore. There is an updated file `NavMenu.tsx` for this. I missed to delete this. Thanks for pointing it out.

2024-11-29 06:31 UTC, Nazeeh21 commented on airdrop/src/hooks/useGetAirdropActive.tsx
> +        // const isActive = await contract.functions.
We dont need this file. I have removed it

2024-11-29 06:34 UTC, Nazeeh21 commented on airdrop/src/routeTree.gen.ts
> +/* prettier-ignore-end */
this file is auto-generated by TanStack Router

2024-12-06 02:36 UTC, calldelegation approved these changes

2024-12-06 07:41 UTC, Nazeeh21 commented on .github/workflows/deploy.yml
> +          VITE_PINATA_JWT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI0MjMzNWE3MC01MmRjLTQyNDgtYjQ2OC1kZTM0YWIxZGVkMWEiLCJlbWFpbCI6Im5hemVlaC54eXpAZ21haWwuY29tIiwiZW1haWx
Yes, it should be. But all the other dapps in the `main` branch are following this conviction, hence had to follow the same. Though, we can definitely add a fix for it in a separate PR

2024-12-06 13:35 UTC, petertonysmith94 commented on .github/workflows/deploy.yml
> +          VITE_PINATA_JWT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI0MjMzNWE3MC01MmRjLTQyNDgtYjQ2OC1kZTM0YWIxZGVkMWEiLCJlbWFpbCI6Im5hemVlaC54eXpAZ21haWwuY29tIiwiZW1haWx
Sounds good to me.

2024-12-06 15:24 UTC, matt-user commented on airdrop/src/routes/__root.tsx
> +                {/* <OnboardingFlowProvider> */}
remove unused comments

2024-12-06 15:24 UTC, matt-user commented on airdrop/src/hooks/useActiveWallet.tsx
> + * Whenever a browser wallet is connected, this hook will return an instance of the browser wallet.
IMO we don't want this.  It is confusing because users can connect with a burner wallet using fuels connectors so why have a burner wallet that is by default already connected.

2024-12-06 15:24 UTC, matt-user commented on airdrop/src/hooks/useClaimAirdrop.ts
> +      console.log(`temp`, temp);
Still not removed

2024-12-06 15:24 UTC, matt-user commented on airdrop/src/utils/airdropEligibility.ts
> +  let temp = undefined;
unresolved

2024-12-10 06:16 UTC, merged